repos:
  # ---------- Python ----------
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks: [id: black]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks: [id: ruff]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks: [id: mypy]

  # ---------- Rust ----------
  - repo: https://github.com/doublify/pre-commit-rust
    rev: 'v1.0'
    hooks:
      - id: fmt
        name: cargo fmt (edge-router)
        entry: bash -c 'cd edge-router && cargo fmt --all -- --check'
        language: system
        types: [rust]

      - id: clippy
        name: cargo clippy (edge-router)
        entry: bash -c 'cd edge-router && cargo clippy'
        language: system
        types: [rust]
        pass_filenames: false
        args: [--all-targets, --all-features, --, -D, warnings, --no-deps]

  # ---------- Go ----------
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-fmt
        name: go-fmt (stt-wrapper)
        entry: bash -c 'cd stt-wrapper && go fmt ./...'
        language: system
        pass_filenames: false

      - id: go-vet
        name: go-vet (stt-wrapper)
        entry: bash -c 'cd stt-wrapper && go vet ./...'
        language: system
        pass_filenames: false

      - id: go-test-mod
        name: go-test-mod (stt-wrapper)
        entry: bash -c 'cd stt-wrapper && go test ./...'
        language: system
        pass_filenames: false

      - id: go-mod-tidy
        name: go-mod-tidy (stt-wrapper)
        entry: bash -c 'cd stt-wrapper && go mod tidy'
        language: system
        pass_filenames: false

  # ---------- Markdown / misc ----------
  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.12.0
    hooks: [id: markdownlint]

